/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vinyls_1.glb -o src/components/VinylModel.tsx -t 
Author: mfb64 (https://sketchfab.com/mfb64)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vinyls-1-159fbaa320324c98af849a49eeae2461
Title: VINYLS 1
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: { [key: string]: THREE.Mesh }
  materials: { [key: string]: THREE.MeshStandardMaterial }
}

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/models/vinyls_1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.129, 0.157, -0.339]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['cover.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.106, 0.157, -0.335]} rotation={[Math.PI / 2, 0.043, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_7.geometry} material={materials['cover.002']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.07, 0.157, -0.332]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['cover.003']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.041, 0.157, -0.335]} rotation={[Math.PI / 2, 0.03, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_13.geometry} material={materials['cover.004']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.013, 0.157, -0.313]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials['cover.005']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.019, 0.157, -0.326]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_19.geometry} material={materials['cover.006']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.046, 0.157, -0.338]} rotation={[Math.PI / 2, 0.021, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_22.geometry} material={materials['cover.007']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.078, 0.157, -0.339]} rotation={[Math.PI / 2, 0.034, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_25.geometry} material={materials['cover.008']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.105, 0.157, -0.33]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_28.geometry} material={materials['cover.009']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.154, 0.156, -0.335]} rotation={[Math.PI / 2, 0.106, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_31.geometry} material={materials['cover.010']} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.135, 0.157, -0.342]} rotation={[Math.PI / 2, 0.019, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_34.geometry} material={materials['cover.011']} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.112, 0.157, -0.335]} rotation={[Math.PI / 2, 0.029, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_37.geometry} material={materials['cover.012']} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.074, 0.157, -0.335]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_40.geometry} material={materials['cover.013']} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.05, 0.157, -0.281]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_43.geometry} material={materials['cover.014']} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.019, 0.157, -0.336]} rotation={[Math.PI / 2, 0.014, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_46.geometry} material={materials['cover.015']} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.015, 0.157, -0.336]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_49.geometry} material={materials['cover.016']} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.042, 0.157, -0.332]} rotation={[Math.PI / 2, 0.025, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_52.geometry} material={materials['cover.017']} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.072, 0.157, -0.335]} rotation={[Math.PI / 2, 0.043, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_55.geometry} material={materials['cover.018']} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.1, 0.157, -0.341]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_58.geometry} material={materials['cover.019']} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.145, 0.157, -0.329]} rotation={[Math.PI / 2, 0.067, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_61.geometry} material={materials['cover.020']} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.14, 0.157, -0.339]} rotation={[Math.PI / 2, 0.026, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_64.geometry} material={materials['cover.021']} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.116, 0.157, -0.335]} rotation={[Math.PI / 2, 0.022, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_67.geometry} material={materials['cover.022']} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.089, 0.157, -0.332]} rotation={[Math.PI / 2, 0.072, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_70.geometry} material={materials['cover.023']} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.054, 0.157, -0.331]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_73.geometry} material={materials['cover.024']} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.025, 0.157, -0.333]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_76.geometry} material={materials['cover.025']} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.011, 0.157, -0.326]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_79.geometry} material={materials['cover.026']} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.035, 0.157, -0.338]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_82.geometry} material={materials['cover.027']} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.062, 0.157, -0.342]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_85.geometry} material={materials['cover.028']} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.096, 0.157, -0.337]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_88.geometry} material={materials['cover.029']} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.131, 0.157, -0.333]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_91.geometry} material={materials['cover.030']} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.143, 0.157, -0.337]} rotation={[Math.PI / 2, 0.026, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_94.geometry} material={materials['cover.031']} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.122, 0.157, -0.335]} rotation={[Math.PI / 2, 0.007, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_97.geometry} material={materials['cover.032']} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.097, 0.157, -0.33]} rotation={[Math.PI / 2, 0.046, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_100.geometry} material={materials['cover.033']} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.06, 0.157, -0.329]} rotation={[Math.PI / 2, 0.014, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_103.geometry} material={materials['cover.034']} />
        <mesh geometry={nodes.Object_104.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.028, 0.157, -0.332]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_106.geometry} material={materials['cover.035']} />
        <mesh geometry={nodes.Object_107.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.001, 0.157, -0.33]} rotation={[Math.PI / 2, 0.043, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_109.geometry} material={materials['cover.036']} />
        <mesh geometry={nodes.Object_110.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.031, 0.157, -0.338]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_112.geometry} material={materials['cover.037']} />
        <mesh geometry={nodes.Object_113.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.059, 0.157, -0.339]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_115.geometry} material={materials['cover.038']} />
        <mesh geometry={nodes.Object_116.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.092, 0.157, -0.335]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_118.geometry} material={materials['cover.039']} />
        <mesh geometry={nodes.Object_119.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.127, 0.157, -0.329]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_121.geometry} material={materials['cover.040']} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.146, 0.157, -0.339]} rotation={[Math.PI / 2, 0.023, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_124.geometry} material={materials['cover.041']} />
        <mesh geometry={nodes.Object_125.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.126, 0.157, -0.335]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_127.geometry} material={materials['cover.042']} />
        <mesh geometry={nodes.Object_128.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.101, 0.157, -0.338]} rotation={[Math.PI / 2, 0.045, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_130.geometry} material={materials['cover.043']} />
        <mesh geometry={nodes.Object_131.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.064, 0.157, -0.334]} rotation={[Math.PI / 2, 0.016, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_133.geometry} material={materials['cover.044']} />
        <mesh geometry={nodes.Object_134.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.037, 0.157, -0.334]} rotation={[Math.PI / 2, 0.03, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_136.geometry} material={materials['cover.045']} />
        <mesh geometry={nodes.Object_137.geometry} material={materials.cardboard} />
      </group>
      <group position={[-0.009, 0.157, -0.326]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_139.geometry} material={materials['cover.046']} />
        <mesh geometry={nodes.Object_140.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.025, 0.157, -0.332]} rotation={[Math.PI / 2, 0.013, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_142.geometry} material={materials['cover.047']} />
        <mesh geometry={nodes.Object_143.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.053, 0.157, -0.336]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_145.geometry} material={materials['cover.048']} />
        <mesh geometry={nodes.Object_146.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.086, 0.157, -0.346]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_148.geometry} material={materials['cover.049']} />
        <mesh geometry={nodes.Object_149.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.116, 0.157, -0.336]} rotation={[Math.PI / 2, 0.047, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_151.geometry} material={materials['cover.050']} />
        <mesh geometry={nodes.Object_152.geometry} material={materials.cardboard} />
      </group>
      <group position={[0, 0.002, 0.095]} rotation={[0, 0.436, 0]}>
        <mesh geometry={nodes.Object_154.geometry} material={materials['cover.051']} />
        <mesh geometry={nodes.Object_155.geometry} material={materials.cardboard} />
      </group>
      <group position={[0.194, 0.002, 0.003]} rotation={[0, -1.468, 0]}>
        <mesh geometry={nodes.Object_157.geometry} material={materials.vinyl} />
        <mesh geometry={nodes.Object_159.geometry} material={materials.label_front} />
        <mesh geometry={nodes.Object_160.geometry} material={materials.label_back} />
        <mesh geometry={nodes.Object_161.geometry} material={materials.label_side} />
      </group>
    </group>
  )
}

useGLTF.preload('/vinyls_1.glb')
