/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vinyl_record_player.glb -o src/components/VinylPlayerModel.tsx -t 
Author: GiraffeTail (https://sketchfab.com/GiraffeTail)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vinyl-record-player-aab1ecd2ccb34bfbac7c6e21a1d6f910
Title: vinyl record player
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/models/vinyl_record_player.glb') as any
  return (
    <group {...props} dispose={null}>
      <group position={[0, 4.389, -0.501]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/vinyl_record_player.glb')
